package:
  name: "transposon_annotation_reasonate"
  version: "1.0.2"

build:
  number: 1

about:
  home: https://github.com/DerKevinRiehl/transposon_annotation_reasonaTE
  license: GPL3
  license_family: GPL
  summary: Transposon Annotator "reasonaTE" - part of TransposonUltimate
  description: Transposon Annotator "reasonaTE" - part of TransposonUltimate
