############################################################################
##### Transposon Annotator reasonaTE - part of Transposon Ultimate #########
##### Kevin Riehl (kevin.riehl.de@gmail.com, 2021) #########################
############################################################################

# Methods
def helpExplanations():
    print("Transposon Annotator \"reasonaTE\" (v1.0, 2021, Kevin Riehl)")
    print("")
    print("USAGE")
    print("  reasonaTE [-help] [-mode]")
    print("")
    print("MODE [1] \"createProject\"")
    print("(mandatory):")
    print("  -projectFolder <String>")
    print("    Directory to create annotation projects in (=annotation workspace)")
    print("  -projectName <String>")
    print("    Desired name of the annotation project")
    print("  -inputFasta <String>")
    print("    Genome file (FASTA) that should be annotated for transposons")
    print("")
    print("MODE [2] \"annotate\"")
    print("(mandatory):")
    print("  -projectFolder <String>")
    print("    Directory with annotation projects (=annotation workspace)")
    print("  -projectName <String>")
    print("    Name of the annotation project")
    print("  -tool <String>")
    print("    Annotation tool that should be used. Possible options: \"helitronScanner\", \"ltrHarvest\", \"mitefind\", \"mitetracker\", \"must\", \"repeatmodel\", \"repMasker\", \"sinefind\", \"sinescan\", \"tirvish\", \"transposonPSI\", \"NCBICDD1000\", \"all\"")
    print("")
    print("MODE [3] \"checkAnnotations\"")
    print("(mandatory):")
    print("  -projectFolder <String>")
    print("    Directory with annotation projects (=annotation workspace)")
    print("  -projectName <String>")
    print("    Name of the annotation project")
    print("")
    print("MODE [4] \"parseAnnotations\"")
    print("(mandatory):")
    print("  -projectFolder <String>")
    print("    Directory with annotation projects (=annotation workspace)")
    print("  -projectName <String>")
    print("    Name of the annotation project")
    print("")
    print("MODE [5] \"checkParsed\"")
    print("(mandatory):")
    print("  -projectFolder <String>")
    print("    Directory with annotation projects (=annotation workspace)")
    print("  -projectName <String>")
    print("    Name of the annotation project")
    print("")    
    print("MODE [6] \"pipeline\"")
    print("(mandatory):")
    print("  -projectFolder <String>")
    print("    Directory with annotation projects (=annotation workspace)")
    print("  -projectName <String>")
    print("    Name of the annotation project")
    print("")   
    print("MODE [7] \"statistics\"")
    print("(mandatory):")
    print("  -projectFolder <String>")
    print("    Directory with annotation projects (=annotation workspace)")
    print("  -projectName <String>")
    print("    Name of the annotation project")
    print("")   
    